"""Render a structured review into a referee report.

Two output formats from the same structure: Markdown for pasting into a journal
submission form, and a self-contained HTML page for reading and printing. The
HTML embeds everything — no network requests — because these reports describe
unpublished manuscripts and should not reach for anything outside the file.
"""

from __future__ import annotations

import html
import urllib.parse
from functools import lru_cache
from pathlib import Path

from .review import ReviewResult
from .schema import RefereeReport

LOGO_PATH = Path(__file__).parent / "web" / "logo.svg"

#: Ink for the watermark. A CSS background image cannot inherit currentColor, so
#: the mark behind the page needs a colour of its own — mid grey reads the same
#: against the light page and the dark one at the opacity it is drawn at.
WATERMARK_INK = "#8a827a"


@lru_cache(maxsize=None)
def _logo(colour: str | None = None) -> str:
    """The PeerNa mark. Inline when it inherits the page ink, otherwise recoloured."""
    svg = LOGO_PATH.read_text(encoding="utf-8").strip()
    return svg if colour is None else svg.replace("currentColor", colour)


def _logo_data_uri() -> str:
    return "url(\"data:image/svg+xml," + urllib.parse.quote(_logo(WATERMARK_INK)) + "\")"


RECOMMENDATION_LABELS = {
    "accept": "Accept",
    "minor_revision": "Minor revision",
    "major_revision": "Major revision",
    "reject": "Reject",
}

STATUS_LABELS = {
    "verified": "verified",
    "not_found": "NOT FOUND",
    "misattributed": "MISATTRIBUTED",
    "unverified": "unverified",
}

#: The corpus this tool consults is the transparent peer review Nature
#: Communications publishes, and each of those files carries CC BY 4.0 — which
#: permits this use outright and asks in return that the source be credited.
#: The referees are anonymous, so what gets credited is the paper and the
#: journal. Nothing of theirs is reproduced: the passes are told to take the
#: expectation and leave the sentence.
PRECEDENT_CREDIT = (
    "Field expectations were drawn from the referee reports published with the "
    "papers below, under CC BY 4.0 "
    "(https://creativecommons.org/licenses/by/4.0/). Nothing from them is "
    "reproduced here."
)

AI_DISCLOSURE = (
    "Generated by an AI peer review tool. Every point should be checked against "
    "the manuscript before being acted on or sent to anyone."
)


def render(result: ReviewResult, manuscript_name: str, mode: str, model_label: str) -> str:
    """A referee report: one opening paragraph, then a numbered list.

    Deliberately plain. Real reports have no section headings, no strengths
    list, no severity labels — adding them would make the output easy to spot as
    machine-written and harder to paste into a journal's form.
    """
    report = result.report
    lines: list[str] = []

    call = RECOMMENDATION_LABELS.get(report.recommendation, report.recommendation)
    lines += [
        f"**{manuscript_name}**",
        "",
        f"**Recommendation: {call}**",
        "",
        report.general_comments.strip(),
        "",
    ]

    for index, comment in enumerate(report.comments, start=1):
        lines += [f"{index}. {comment.text.strip()}", ""]

    lines += _appendix_lines(report, result, model_label)
    return "\n".join(lines)


def _appendix_lines(report: RefereeReport, result: ReviewResult, model_label: str) -> list[str]:
    """Citation checks, then the run's own metadata.

    Citations get their own heading rather than being folded into the numbered
    comments: a referee does not normally audit a bibliography, so presenting it
    as part of the review would misrepresent what it is, and burying it as a
    footnote would waste the one thing here a human reviewer rarely does.
    """
    lines = ["---", "", "**Citations checked**", "", _coverage_line(report), ""]
    if report.citation_checks:
        for check in report.citation_checks:
            status = STATUS_LABELS.get(check.status, check.status)
            entry = f"- **[{status}]** {check.reference} — {check.location}"
            if check.note.strip():
                entry += f"\n  - {check.note.strip()}"
            lines.append(entry)
        lines.append("")
    lines += [
        f"_Reviewer confidence: {report.confidence}._",
        "",
        f"_{AI_DISCLOSURE} Model: {model_label}._",
        "",
    ]
    lines += _credit_lines(result)
    if result.warnings:
        lines += ["", "**Run warnings**", ""]
        lines += [f"- {w}" for w in dict.fromkeys(result.warnings)]
        lines.append("")
    return lines


def render_pass_notes(result: ReviewResult) -> str:
    """The raw per-pass findings, for when the synthesis drops something."""
    from .passes import PASSES

    lines = ["# Per-pass notes", ""]
    if result.pass_notes.get("precedent"):
        lines += [
            "## What referees expect of papers like this",
            "",
            f"_Sources: {result.pass_notes.get('precedent_sources', '')}_",
            "",
            result.pass_notes["precedent"],
            "",
        ]
    for review_pass in PASSES:
        lines += [
            f"## {review_pass.title}",
            "",
            result.pass_notes.get(review_pass.key, "(no findings)"),
            "",
        ]
    return "\n".join(lines)


# --------------------------------------------------------------------- HTML

STYLES = """
:root {
  color-scheme: light dark;
  --bg: #fbfaf9;
  --panel: #ffffff;
  --ink: #1a1815;
  --muted: #6b6560;
  --rule: #e3ded8;
  --major: #a02c2c;
  --major-bg: #fdf3f2;
  --minor: #8a6d1f;
  --minor-bg: #fdf9ee;
  --ok: #2f6b46;
  --alarm: #a02c2c;
  --alarm-bg: #fdf3f2;
}
@media (prefers-color-scheme: dark) {
  :root {
    --bg: #161513;
    --panel: #1e1d1a;
    --ink: #eae6e0;
    --muted: #9b948c;
    --rule: #33302b;
    --major: #f08b84;
    --major-bg: #2a1c1b;
    --minor: #d9b95f;
    --minor-bg: #262015;
    --ok: #7dc79b;
    --alarm: #f08b84;
    --alarm-bg: #2a1c1b;
  }
}
* { box-sizing: border-box; }
body {
  margin: 0;
  padding: 3rem 1.5rem 5rem;
  background: var(--bg);
  color: var(--ink);
  font: 16px/1.65 ui-serif, Georgia, "Times New Roman", serif;
}
main { max-width: 46rem; margin: 0 auto; }
header { border-bottom: 2px solid var(--ink); padding-bottom: 1.25rem; margin-bottom: 2.5rem; }
h1 { font-size: 1.7rem; line-height: 1.25; margin: 0 0 .4rem; font-weight: 600; }
.wordmark {
  display: flex; align-items: center; gap: .4rem; margin: 0;
  color: var(--muted); font-size: .95rem; letter-spacing: .02em;
  font-family: ui-sans-serif, system-ui, sans-serif;
}
.wordmark svg { width: 1.05rem; height: 1.05rem; flex: none; }

/* The bud, very faint, behind the text. Fixed rather than absolute so that a
   browser printing this repeats it on every page instead of only the first. */
.watermark {
  position: fixed; inset: 0; z-index: -1; pointer-events: none;
  background: center / 40vmin no-repeat;
  background-image: var(--watermark);
  opacity: .035;
}
h2 {
  font-size: .78rem; text-transform: uppercase; letter-spacing: .1em; font-weight: 700;
  font-family: ui-sans-serif, system-ui, sans-serif;
  color: var(--muted); margin: 2.75rem 0 .9rem;
  padding-bottom: .4rem; border-bottom: 1px solid var(--rule);
}
p { margin: 0 0 1rem; }
ul { margin: 0 0 1rem; padding-left: 1.2rem; }
li { margin-bottom: .4rem; }

.verdict {
  font-family: ui-sans-serif, system-ui, sans-serif; font-size: .95rem;
  margin: 0 0 1rem; padding: .55rem .9rem; border-radius: 5px;
  background: var(--panel); border: 1px solid var(--rule);
  border-left: 4px solid var(--major);
}
.general { font-size: 1.02rem; margin-bottom: 2rem; }
ol.comments { padding-left: 1.5rem; margin: 0 0 2.5rem; }
ol.comments li { margin-bottom: 1.15rem; padding-left: .35rem; }
ol.comments li::marker { font-weight: 700; color: var(--muted); }
ol.comments li.major::marker { color: var(--major); }
.appendix { border-top: 1px solid var(--rule); padding-top: 1.3rem; margin-top: 1rem; font-size: .92rem; }
.appendix h2 { margin-top: 1.3rem; }
.verdictLine { font-family: ui-sans-serif, system-ui, sans-serif; font-size: .92rem; }
.disclosure { color: var(--muted); font-size: .82rem; font-family: ui-sans-serif, system-ui, sans-serif; }

.concern { border-left: 3px solid var(--rule); padding: 0 0 .1rem 1.1rem; margin-bottom: 1.9rem; }
.concern.major { border-left-color: var(--major); }
.concern.minor { border-left-color: var(--minor); }
.concern .where {
  font-family: ui-sans-serif, system-ui, sans-serif; font-size: .8rem; font-weight: 700;
  letter-spacing: .02em; display: block; margin-bottom: .3rem;
}
.concern.major .where { color: var(--major); }
.concern.minor .where { color: var(--minor); }
.concern .issue { font-weight: 600; }
.concern dl { margin: .7rem 0 0; }
.concern dt {
  font-family: ui-sans-serif, system-ui, sans-serif; font-size: .72rem;
  text-transform: uppercase; letter-spacing: .07em; color: var(--muted); margin-top: .7rem;
}
.concern dd { margin: .15rem 0 0; }

.tag {
  display: inline-block; font-family: ui-sans-serif, system-ui, sans-serif;
  font-size: .68rem; font-weight: 700; text-transform: uppercase; letter-spacing: .06em;
  padding: .12rem .45rem; border-radius: 3px; border: 1px solid currentColor; vertical-align: .08em;
}
.tag.major { color: var(--major); background: var(--major-bg); }
.tag.minor { color: var(--minor); background: var(--minor-bg); }
.tag.verified { color: var(--ok); }
.tag.unverified, .tag.not_found, .tag.misattributed { color: var(--alarm); background: var(--alarm-bg); }

.citation { margin-bottom: 1.1rem; }
.citation .ref { font-weight: 600; }
.citation .note { color: var(--muted); font-size: .93rem; margin: .25rem 0 0; }

.verdict {
  background: var(--panel); border: 1px solid var(--rule);
  border-left: 4px solid var(--ink); padding: 1.3rem 1.5rem; margin-top: .5rem;
}
.verdict .call {
  font-family: ui-sans-serif, system-ui, sans-serif; font-size: 1.15rem;
  font-weight: 700; margin: 0 0 .6rem;
}
.verdict .confidence {
  font-family: ui-sans-serif, system-ui, sans-serif; font-size: .8rem;
  color: var(--muted); margin: .8rem 0 0;
}
.callout {
  background: var(--alarm-bg); border: 1px solid var(--alarm); color: var(--alarm);
  padding: .8rem 1rem; margin: 1rem 0; font-size: .9rem;
  font-family: ui-sans-serif, system-ui, sans-serif;
}
.callout p { margin: 0; }
.empty { color: var(--muted); font-style: italic; }
.credit {
  margin: .4rem 0 0; padding-left: 1.1rem;
  color: var(--muted); font-size: .78rem; line-height: 1.6;
  font-family: ui-sans-serif, system-ui, sans-serif;
}
footer {
  margin-top: 3.5rem; padding-top: 1.2rem; border-top: 1px solid var(--rule);
  color: var(--muted); font-size: .82rem;
  font-family: ui-sans-serif, system-ui, sans-serif;
}
@media print {
  body { background: #fff; color: #000; padding: 0; font-size: 11pt; }
  /* Browsers drop background images when printing unless told not to. */
  .watermark {
    background-size: 7cm; opacity: .06;
    -webkit-print-color-adjust: exact; print-color-adjust: exact;
  }
  .concern, .citation, .verdict { break-inside: avoid; }
  h2 { break-after: avoid; }
  footer { break-before: avoid; }
}
"""


def render_html(
    result: ReviewResult, manuscript_name: str, mode: str, model_label: str
) -> str:
    report = result.report
    e = html.escape
    out: list[str] = []

    title = f"Referee report — {manuscript_name}"

    out.append("<!doctype html>")
    out.append('<html lang="en"><head><meta charset="utf-8">')
    out.append('<meta name="viewport" content="width=device-width, initial-scale=1">')
    out.append(f"<title>{e(title)}</title>")
    out.append(f"<style>:root{{--watermark:{_logo_data_uri()};}}{STYLES}</style>")
    out.append("</head><body><main>")

    out.append('<div class="watermark" aria-hidden="true"></div>')
    out.append(f"<header><h1>{e(title)}</h1>")
    out.append(f'<p class="wordmark">{_logo()}<span>PeerNa</span></p>')
    out.append("</header>")

    call = RECOMMENDATION_LABELS.get(report.recommendation, report.recommendation)
    out.append(f'<p class="verdict">Recommendation: <strong>{e(call)}</strong></p>')
    out.append(f'<p class="general">{e(report.general_comments.strip())}</p>')

    out.append('<ol class="comments">')
    for comment in report.comments:
        out.append(f'<li class="{comment.severity}">{e(comment.text.strip())}</li>')
    out.append("</ol>")

    out.append('<section class="appendix">')
    out.append("<h2>Citations checked</h2>")
    out.append(f'<p class="note">{e(_coverage_line(report))}</p>')
    if report.citation_checks:
        for check in report.citation_checks:
            label = STATUS_LABELS.get(check.status, check.status)
            out.append(
                f'<div class="citation">'
                f'<span class="tag {check.status}">{e(label)}</span> '
                f'<span class="ref">{e(check.reference)}</span> '
                f'<span class="note">— {e(check.location)}</span>'
            )
            if check.note.strip():
                out.append(f'<p class="note">{e(check.note.strip())}</p>')
            out.append("</div>")

    out.append(
        f'<p class="verdictLine">Reviewer confidence: {e(report.confidence)}</p>'
    )

    if result.warnings:
        out.append("<h2>Run warnings</h2><ul>")
        out.extend(f"<li>{e(w)}</li>" for w in dict.fromkeys(result.warnings))
        out.append("</ul>")

    out.append(f'<p class="disclosure">{e(AI_DISCLOSURE)} Model: {e(model_label)}.</p>')
    sources = _credit_sources(result)
    if sources:
        out.append(f'<p class="disclosure">{e(PRECEDENT_CREDIT)}</p>')
        out.append('<ul class="credit">')
        for line in sources:
            out.append(f"<li>{e(line)}</li>")
        out.append("</ul>")
    out.append("</section>")
    out.append("</main></body></html>")
    return "\n".join(out)


def _credit_sources(result: ReviewResult) -> list[str]:
    raw = result.pass_notes.get("precedent_sources") or ""
    return [line.strip() for line in raw.splitlines() if line.strip()]


def _credit_lines(result: ReviewResult) -> list[str]:
    sources = _credit_sources(result)
    if not sources:
        return []
    return ["", f"_{PRECEDENT_CREDIT}_", ""] + [f"- {s}" for s in sources] + [""]


def _coverage_line(report: RefereeReport) -> str:
    """Say how much of the bibliography was examined.

    Without this the list reads as the whole story. It is not: absence from a
    list of eight checked citations says nothing about the other fifty.
    """
    checked = len(report.citation_checks)
    total = report.references_total
    if not checked:
        return (
            "No citation was verified in this run."
            + (f" The manuscript lists about {total} references." if total else "")
        )
    if total and total >= checked:
        return (
            f"{checked} of about {total} references were examined. The rest were "
            "not looked at — absence from this list is not evidence that a "
            "citation is sound."
        )
    return (
        f"{checked} reference(s) were examined. The rest of the bibliography was "
        "not looked at."
    )
